name = "RHSVI"
uuid = "7d4c78ca-f647-492d-a5fe-ed5856807cff"
authors = ["Merlijn Krale"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
